const productos = [
  {
    id: 1,
    nombre: "Perro",
    categoria: "Sonajero",
    precio: 6400,
    imagen: "../asset/1.Sonajero_Perro.png",
  },
  {
    id: 2,
    nombre: "Gato",
    categoria: "Sonajero",
    precio: 7300,
    imagen: "../asset/1.Sonajero_Perro.png",
  },
  {
    id: 3,
    nombre: "Elefante",
    categoria: "Peluche",
    precio: 8500,
    imagen: "../asset/1.Sonajero_Perro.png",
  },
  {
    id: 4,
    nombre: "Sonajero Perro",
    categoria: "Sonajero",
    precio: 6400,
    imagen: "../asset/1.Sonajero_Perro.png",
  },
  {
    id: 5,
    nombre: "Sonajero Perro",
    categoria: "Sonajero",
    precio: 6400,
    imagen: "../asset/1.Sonajero_Perro.png",
  },
  {
    id: 6,
    nombre: "Sonajero Perro",
    categoria: "Sonajero",
    precio: 6400,
    imagen: "../asset/1.Sonajero_Perro.png",
  },
  {
    id: 7,
    nombre: "Sonajero Perro",
    categoria: "Sonajero",
    precio: 6400,
    imagen: "../asset/1.Sonajero_Perro.png",
  },
  {
    id: 8,
    nombre: "Sonajero Perro",
    categoria: "Sonajero",
    precio: 6400,
    imagen: "../asset/1.Sonajero_Perro.png",
  },
  {
    id: 9,
    nombre: "Sonajero Perro",
    categoria: "Sonajero",
    precio: 6400,
    imagen: "../asset/1.Sonajero_Perro.png",
  },
];
